@startuml sprint2
title Sprint 2 — Justificatifs & Consultation\nAttendanceFlow-AMS

left to right direction

skinparam usecase {
  BackgroundColor #EAFAF1
  BorderColor #1E8449
  ArrowColor #1E8449
}
skinparam actor {
  BorderColor #1E8449
  BackgroundColor #D5F5E3
}

actor "Étudiant" as Student
actor "Administrateur" as Admin

rectangle "Sprint 2 — Justificatifs & Consultation (Focus Web Platform)" {
  usecase "S'authentifier" as UC01
  usecase "Soumettre un justificatif (Web)" as UC04
  usecase "Valider / Réfuter un justificatif (Web)" as UC06
  usecase "Exporter les rapports (Web)" as UC07
  
  usecase "Consulter sses absences (Mobile - Rapide / Web - Complet)" as UC05
  
  UC04 ..> UC01 : <<include>>
  UC05 ..> UC01 : <<include>>
  UC06 ..> UC01 : <<include>>
  UC07 ..> UC01 : <<include>>
}

Student -- UC04
Student -- UC05

Admin -- UC06
Admin -- UC07

@enduml
