@startuml sprint1
title Sprint 1 (MVP) — Digitalisation du Pointage\nAttendanceFlow-AMS

left to right direction

skinparam usecase {
  BackgroundColor #FCF3CF
  BorderColor #F1C40F
  ArrowColor #F1C40F
}
skinparam actor {
  BorderColor #F1C40F
  BackgroundColor #FEF9E7
}

actor "Formateur" as Trainer
actor "Administrateur" as Admin

rectangle "Sprint 1 — MVP Attendance (Application Mobile & Web)" {
  usecase "S'authentifier" as UC01
  usecase "Pointage par session\n(9-11, 11-14, 14-17)" as UC02
  usecase "Saisir motif de retard" as UC02a
  usecase "Visualiser les présences\nen temps réel" as UC03

  UC02 ..> UC01 : <<include>>
  UC03 ..> UC01 : <<include>>
  UC02 <.. UC02a : <<extend>>
}

Trainer -- UC02
Admin -- UC02
Admin -- UC03

@enduml
