@startuml use_case_divided
title Diagramme de Cas d'Utilisation - AttendanceFlow-AMS (Web vs Mobile)

left to right direction

skinparam usecase {
  BackgroundColor #EBF5FB
  BorderColor #2E86C1
}
skinparam actor {
  BorderColor #2E86C1
  BackgroundColor #D6EAF8
}

actor "Administrateur" as Admin
actor "Formateur" as Trainer
actor "Étudiant" as Student

rectangle "Application Mobile (Opérations de Terrain)" {
    usecase "S'authentifier (Mobile)" as UC_M01
    usecase "Pointer les absences" as UC_M02
    usecase "Saisir un motif de retard" as UC_M02a
    usecase "Consulter ses absences (Rapide)" as UC_M06
}

rectangle "Platforme Web (Gestion Complète)" {
    usecase "S'authentifier (Web)" as UC_W01
    usecase "Visualiser le Dashboard" as UC_W03
    usecase "Soumettre un justificatif" as UC_W04
    usecase "Gérer les justificatifs" as UC_W05
    usecase "Valider / Réfuter un justificatif" as UC_W05a
    usecase "Exporter les rapports" as UC_W07
    usecase "Historique d'assiduité complet" as UC_W06
    
    ' Functions shared with mobile but accessible on web too
    usecase "Gestion des absences" as UC_W_ABS
}

' Relations Mobile
Trainer -- UC_M02
Admin -- UC_M02
UC_M02 <.. UC_M02a : <<extend>>
Student -- UC_M06

' Relations Web
Admin -- UC_W03
Admin -- UC_W05
Admin -- UC_W07
UC_W05 <.. UC_W05a : <<extend>>

Student -- UC_W04
Student -- UC_W06

' Shared Logic
Trainer -- UC_W_ABS
Admin -- UC_W_ABS

@enduml