@startuml sprint1_web
title Sprint 1 - Plateforme Web + Mobile MVP 
left to right direction

skinparam usecase {
  BackgroundColor #FCF3CF
  BorderColor #F1C40F
}

actor "Administrateur" as Admin
actor "Formateur" as Trainer
actor "Étudiant" as Student

rectangle "Web - Sprint 1 (MVP)" {
    usecase "S'authentifier" as UC_W01
    usecase "Gestion avancée des absences" as UC_W_ABS
    usecase "Visualiser le Dashboard (Lecture seule)" as UC_W03
    usecase "Créer ses séances\n(Modules/Groups assignés)" as UC_W08
}

rectangle "Mobile - Sprint 1 (MVP)" {
    usecase "Consulter les absences (Mobile)" as UC_M05
    usecase "Consulter ses absences (Mobile)" as UC_M06
}

Admin -- UC_W_ABS
Admin -- UC_W03
Admin -- UC_M05

Trainer -- UC_W_ABS
Trainer -- UC_W08

Student -- UC_M06

UC_W08 ..> UC_W01 : <<include>>
UC_W_ABS ..> UC_W01 : <<include>>
UC_W03 ..> UC_W01 : <<include>>


@enduml
