@startuml sprint1_web
title Sprint 1 - Plateforme Web (Digitalisation de base)
left to right direction

skinparam usecase {
  BackgroundColor #FCF3CF
  BorderColor #F1C40F
}

actor "Administrateur" as Admin
actor "Formateur" as Trainer

rectangle "Web - Sprint 1" {
    usecase "S'authentifier" as UC_W01
    usecase "Gestion avancée des absences" as UC_W_ABS
    usecase "Visualiser le Dashboard (Lecture seule)" as UC_W03
}

Admin -- UC_W01
Admin -- UC_W_ABS
Admin -- UC_W03

Trainer -- UC_W01
Trainer -- UC_W_ABS

@enduml
