@startuml sprint3_web
title Sprint 3 - QR Attendance, IA & Mobile Interactions
left to right direction

skinparam usecase {
  BackgroundColor #F5EEF8
  BorderColor #8E44AD
}

actor "Administrateur" as Admin
actor "Étudiant" as Student
actor "Formateur" as Trainer

rectangle "Web - Sprint 3" {
    usecase "Générer une analyse IA des rapports\n(Modèle IA d'absentéisme & Synthèse)" as UC_W_AI
    usecase "Exporter les rapports de synthèse\n(PDF, Excel)" as UC_W07R
    usecase "Exporter la liste des étudiants\net l'historique des absences\n(Excel)" as UC_W07
}

rectangle "Mobile - Sprint 3" {
    usecase "Pointer par scan QR" as UC_M02
    usecase "Saisir motif de retard" as UC_M02a
}

' Web Links
Admin -- UC_W_AI
Trainer -- UC_W_AI
Admin -- UC_W07R
Trainer -- UC_W07R
Admin -- UC_W07
Trainer -- UC_W07

' Mobile Links
Student -- UC_M02

UC_M02 <.. UC_M02a : <<extend>>



@enduml
