@startuml sprint2_web
title Sprint 2 - Plateforme Web + Mobile 
left to right direction

skinparam usecase {
  BackgroundColor #EAFAF1
  BorderColor #1E8449
}

actor "Administrateur" as Admin
actor "Étudiant" as Student
actor "Formateur" as Trainer

rectangle "Web - Sprint 2" {
    usecase "Soumettre un justificatif" as UC_W04
    usecase "Joindre un document justificatif" as UC_W04a
    usecase "Gérer les justificatifs (Validation)" as UC_W05
    usecase "Valider / Réfuter un justificatif" as UC_W05a
    usecase "Consulter l'historique d'assiduité\net statistiques" as UC_W06
    usecase "Recevoir des notifications" as UC_W09
    usecase "Générer le QR code d'une séance" as UC_W09_QR
}

rectangle "Mobile - Sprint 2" {
    usecase "Consulter ses sessions" as UC_M08
    usecase "Soumettre un justificatif" as UC_M04
    usecase "Recevoir des notifications" as UC_M09
    usecase "Soumettre un justificatif" as UC_M03
    usecase "Scanner le QR Code\npour enregistrer la présence" as UC_M10_QR
}

' Web Links
Admin -- UC_W05
Admin -- UC_W09
Admin -- UC_W09_QR
Admin -- UC_W06
Student -- UC_W04
Student -- UC_W06
Student -- UC_W09
Trainer -- UC_W09
Trainer -- UC_W09_QR
Trainer -- UC_W06

' Mobile Links
Student -- UC_M09
Student -- UC_M03
Student -- UC_M08
Student -- UC_M04
Student -- UC_M10_QR

' Web Relationships

UC_W04 <.. UC_W04a : <<extend>>
UC_W05 <.. UC_W05a : <<extend>>

' Mobile Relationships


@enduml
